### ISSUE TITLE
Inputbox issue

### ISSUE THREAD

**Issue by ThomTrab** [estatio/estatio#10]
Hi,

I'm trying to look at estatio. I successfully compile it and able to launch it with:
`mvn jetty:run`

When I go to:
`http://localhost:8080/estatio-webapp/wicket`
I'm able to login but after that if I try to type some text in any (at least that I tested) text input box nothing happend. Meaning the text did not appear in the input box.

I'm using Firefox 36.0.1 under Linux Mint (Ubuntu).  Any guess ?

Thanks

**Comment by martin-g** [comment]
Hi,

Could you please try to reproduce with Isis Simple app ?
http://isis.apache.org/intro/getting-started/simpleapp-archetype.html

**Comment by ThomTrab** [comment]
Isis Simple app work just fine. I'm able to input text and so create object

I don't know if it's related but I can't launch estatio with `java -jar webapp/target/estatio-webapp-0.0.1-SNAPSHOT-jetty-console.war` because the war file does not exist.

**Comment by danhaywood** [comment]
Thanks for taking the time to look at Estatio.

My guess is that you need to load up some sample (fixture) data.  Unless
you've changed settings in WEB-INF/persistor.properties, Estatio will be
running against an in-memory DB.  The schema for this is created at start
up, but the tables will be empty.  This is probably what you're seeing
whenever you go searching for some data - nothing there.

The fix is easy: load some sample data.  You can do this with:

         Prototyping > Run Property/Lease Fixture Script, then choose
"Estatio Demo Fixture" from the drop-down, and hit OK.

This will result in a transcript of all the stuff that's been created.  You
can either navigate from there and explore, or alternatively something like:

         Leases > All Lease

or

          Properties > All Properties

to start browsing through the data.

~~~
If you can't see the "Prototyping" menu, make sure you've logged in as
estatio-admin/pass, and in WEB-INF/web.xml, the "configuration"
context-param should be set to "development" (so that the "prototyping"
actions for demos etc) are visible.

     <context-param>
         <param-name>configuration</param-name>
         <param-value>development</param-value>
     </context-param>


HTH
Dan



On 13 March 2015 at 16:13, ThomTrab <notifications@github.com> wrote:

> Isis Simple app work just fine. I'm able to input text and so create object
>
> I don't know if it's related but I can't launch estatio with java -jar
> webapp/target/estatio-webapp-0.0.1-SNAPSHOT-jetty-console.war because the
> war file does not exist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/estatio/estatio/issues/10#issuecomment-79087748>.
>

**Comment by ThomTrab** [comment]
I may not explain clearly my issue.

I'm able to login to the app, launch the script, everyhting look fine but if I want to, let say, create a `New property`, the pop-up open but when I try to type some text in it nothing appear for either of the input boxes even for the date.

Thanks for your help

**Comment by martin-g** [comment]
You may try with another browser.
Also check for JavaScript errors in the JavaScript console.

**Comment by ThomTrab** [comment]
I found my issue. It's due to padding in the CSS sheet:
`.input-sm, .form-horizontal .form-group-sm .form-control {
    padding: 15px 10px;
}` in `http://localhost:8080/estatio-webapp/wicket/wicket/resource/de.agilecoders.wicket.themes.markup.html.bootswatch.BootswatchCssReference/css/bootstrap.sandstone-ver-1426182893000.css` line 6215.

if I disable it in Firebug, I can see the text in the input box.

Strange, no ?

**Comment by danhaywood** [comment]
Would be good to see a recording or screenshot of that... Estatio works
fine for us in Chrome/IE/Firefox on Mac/Win/Ubuntu....
