### ISSUE TITLE
Need guide about startup...

### ISSUE THREAD

**Issue by Meirtz** [estatio/estatio#13]
Hi:
	I am a developer who is working on project Estatio, and these days while I was working with it I’ve got these problems:
		1) No references to be selected when creating new item (It tells me “Doesn’t match pattern." );
		2) Cannot install fixtures and return first role because it throws an unexpected error (Details show below);
		3) I wonder if there’s any tutorials or user guide or  any other document on setting and modifying this great masterpieces.
	Forgive my poor English and really sorry about distributing you. Thank you for providing us such great craft. I am really looking forward to your reply and any reply I will appreciate it.

Sincerely
Chevalier Meirtz

**Comment by danhaywood** [comment]
Chevalier contacted me directly also, with the same issue, but also included the stack trace.  Copying it below.  

Basically, seems that the FixtureScripts domain service is not available.

<pre>
Sorry, an unexpected error occurred.
Stack trace:
org.apache.wicket.WicketRuntimeException
Method onRequest of interface org.apache.wicket.behavior.IBehaviorListener targeted at org.apache.wicket.ajax.markup.html.AjaxLink$1@f2a5088 on component [AjaxLink [Component id = menuLink]] threw an exception
org.apache.wicket.RequestListenerInterface#internalInvoke(RequestListenerInterface.java:268)
org.apache.wicket.RequestListenerInterface#invoke(RequestListenerInterface.java:241)
org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler#invokeListener(ListenerInterfaceRequestHandler.java:250)
org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler#respond(ListenerInterfaceRequestHandler.java:236)
org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor#respond(RequestCycle.java:890)
org.apache.wicket.request.RequestHandlerStack#execute(RequestHandlerStack.java:64)
org.apache.wicket.request.cycle.RequestCycle#execute(RequestCycle.java:261)
org.apache.wicket.request.cycle.RequestCycle#processRequest(RequestCycle.java:218)
org.apache.wicket.request.cycle.RequestCycle#processRequestAndDetach(RequestCycle.java:289)
org.apache.wicket.protocol.http.WicketFilter#processRequestCycle(WicketFilter.java:259)
org.apache.wicket.protocol.http.WicketFilter#processRequest(WicketFilter.java:201)
org.apache.wicket.protocol.http.WicketFilter#doFilter(WicketFilter.java:282)
org.eclipse.jetty.servlet.ServletHandler$CachedChain#doFilter(ServletHandler.java:1667)
org.apache.shiro.web.servlet.AbstractShiroFilter#executeChain(AbstractShiroFilter.java:449)
org.apache.shiro.web.servlet.AbstractShiroFilter$1#call(AbstractShiroFilter.java:365)
org.apache.shiro.subject.support.SubjectCallable#doCall(SubjectCallable.java:90)
org.apache.shiro.subject.support.SubjectCallable#call(SubjectCallable.java:83)
org.apache.shiro.subject.support.DelegatingSubject#execute(DelegatingSubject.java:383)
org.apache.shiro.web.servlet.AbstractShiroFilter#doFilterInternal(AbstractShiroFilter.java:362)
org.apache.shiro.web.servlet.OncePerRequestFilter#doFilter(OncePerRequestFilter.java:125)
org.eclipse.jetty.servlet.ServletHandler$CachedChain#doFilter(ServletHandler.java:1667)
org.eclipse.jetty.servlet.ServletHandler#doHandle(ServletHandler.java:581)
org.eclipse.jetty.server.handler.ScopedHandler#handle(ScopedHandler.java:143)
org.eclipse.jetty.security.SecurityHandler#handle(SecurityHandler.java:548)
org.eclipse.jetty.server.session.SessionHandler#doHandle(SessionHandler.java:226)
org.eclipse.jetty.server.handler.ContextHandler#doHandle(ContextHandler.java:1114)
org.eclipse.jetty.servlet.ServletHandler#doScope(ServletHandler.java:511)
org.eclipse.jetty.server.session.SessionHandler#doScope(SessionHandler.java:185)
org.eclipse.jetty.server.handler.ContextHandler#doScope(ContextHandler.java:1048)
org.eclipse.jetty.server.handler.ScopedHandler#handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.ContextHandlerCollection#handle(ContextHandlerCollection.java:213)
org.eclipse.jetty.server.handler.HandlerCollection#handle(HandlerCollection.java:109)
org.eclipse.jetty.server.handler.HandlerWrapper#handle(HandlerWrapper.java:119)
org.eclipse.jetty.server.Server#handle(Server.java:517)
org.eclipse.jetty.server.HttpChannel#handle(HttpChannel.java:302)
org.eclipse.jetty.server.HttpConnection#onFillable(HttpConnection.java:242)
org.eclipse.jetty.io.AbstractConnection$ReadCallback#succeeded(AbstractConnection.java:245)
org.eclipse.jetty.io.FillInterest#fillable(FillInterest.java:95)
org.eclipse.jetty.io.SelectChannelEndPoint$2#run(SelectChannelEndPoint.java:75)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume#produceAndRun(ExecuteProduceConsume.java:213)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume#run(ExecuteProduceConsume.java:147)
org.eclipse.jetty.util.thread.QueuedThreadPool#runJob(QueuedThreadPool.java:654)
org.eclipse.jetty.util.thread.QueuedThreadPool$3#run(QueuedThreadPool.java:572)
java.lang.Thread#run(Thread.java:745)
Caused by:
java.lang.reflect.InvocationTargetException
sun.reflect.NativeMethodAccessorImpl#invoke0(NativeMethodAccessorImpl.java:-2)
sun.reflect.NativeMethodAccessorImpl#invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl#invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method#invoke(Method.java:497)
org.apache.wicket.RequestListenerInterface#internalInvoke(RequestListenerInterface.java:258)
org.apache.wicket.RequestListenerInterface#invoke(RequestListenerInterface.java:241)
org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler#invokeListener(ListenerInterfaceRequestHandler.java:250)
org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler#respond(ListenerInterfaceRequestHandler.java:236)
org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor#respond(RequestCycle.java:890)
org.apache.wicket.request.RequestHandlerStack#execute(RequestHandlerStack.java:64)
org.apache.wicket.request.cycle.RequestCycle#execute(RequestCycle.java:261)
org.apache.wicket.request.cycle.RequestCycle#processRequest(RequestCycle.java:218)
org.apache.wicket.request.cycle.RequestCycle#processRequestAndDetach(RequestCycle.java:289)
org.apache.wicket.protocol.http.WicketFilter#processRequestCycle(WicketFilter.java:259)
org.apache.wicket.protocol.http.WicketFilter#processRequest(WicketFilter.java:201)
org.apache.wicket.protocol.http.WicketFilter#doFilter(WicketFilter.java:282)
org.eclipse.jetty.servlet.ServletHandler$CachedChain#doFilter(ServletHandler.java:1667)
org.apache.shiro.web.servlet.AbstractShiroFilter#executeChain(AbstractShiroFilter.java:449)
org.apache.shiro.web.servlet.AbstractShiroFilter$1#call(AbstractShiroFilter.java:365)
org.apache.shiro.subject.support.SubjectCallable#doCall(SubjectCallable.java:90)
org.apache.shiro.subject.support.SubjectCallable#call(SubjectCallable.java:83)
org.apache.shiro.subject.support.DelegatingSubject#execute(DelegatingSubject.java:383)
org.apache.shiro.web.servlet.AbstractShiroFilter#doFilterInternal(AbstractShiroFilter.java:362)
org.apache.shiro.web.servlet.OncePerRequestFilter#doFilter(OncePerRequestFilter.java:125)
org.eclipse.jetty.servlet.ServletHandler$CachedChain#doFilter(ServletHandler.java:1667)
org.eclipse.jetty.servlet.ServletHandler#doHandle(ServletHandler.java:581)
org.eclipse.jetty.server.handler.ScopedHandler#handle(ScopedHandler.java:143)
org.eclipse.jetty.security.SecurityHandler#handle(SecurityHandler.java:548)
org.eclipse.jetty.server.session.SessionHandler#doHandle(SessionHandler.java:226)
org.eclipse.jetty.server.handler.ContextHandler#doHandle(ContextHandler.java:1114)
org.eclipse.jetty.servlet.ServletHandler#doScope(ServletHandler.java:511)
org.eclipse.jetty.server.session.SessionHandler#doScope(SessionHandler.java:185)
org.eclipse.jetty.server.handler.ContextHandler#doScope(ContextHandler.java:1048)
org.eclipse.jetty.server.handler.ScopedHandler#handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.ContextHandlerCollection#handle(ContextHandlerCollection.java:213)
org.eclipse.jetty.server.handler.HandlerCollection#handle(HandlerCollection.java:109)
org.eclipse.jetty.server.handler.HandlerWrapper#handle(HandlerWrapper.java:119)
org.eclipse.jetty.server.Server#handle(Server.java:517)
org.eclipse.jetty.server.HttpChannel#handle(HttpChannel.java:302)
org.eclipse.jetty.server.HttpConnection#onFillable(HttpConnection.java:242)
org.eclipse.jetty.io.AbstractConnection$ReadCallback#succeeded(AbstractConnection.java:245)
org.eclipse.jetty.io.FillInterest#fillable(FillInterest.java:95)
org.eclipse.jetty.io.SelectChannelEndPoint$2#run(SelectChannelEndPoint.java:75)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume#produceAndRun(ExecuteProduceConsume.java:213)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume#run(ExecuteProduceConsume.java:147)
org.eclipse.jetty.util.thread.QueuedThreadPool#runJob(QueuedThreadPool.java:654)
org.eclipse.jetty.util.thread.QueuedThreadPool$3#run(QueuedThreadPool.java:572)
java.lang.Thread#run(Thread.java:745)
Caused by:
java.lang.NullPointerException
org.estatio.fixture.security.EstatioSecurityModuleFixturesService#installFixturesAndReturnFirstRole(EstatioSecurityModuleFixturesService.java:90)
sun.reflect.NativeMethodAccessorImpl#invoke0(NativeMethodAccessorImpl.java:-2)
sun.reflect.NativeMethodAccessorImpl#invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl#invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method#invoke(Method.java:497)
org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract#internalInvoke(ActionInvocationFacetForDomainEventAbstract.java:407)
org.apache.isis.core.metamodel.facets.actions.action.invocation.ActionInvocationFacetForDomainEventAbstract#invoke(ActionInvocationFacetForDomainEventAbstract.java:212)
org.apache.isis.core.runtime.transaction.facets.ActionInvocationFacetWrapTransaction$1#execute(ActionInvocationFacetWrapTransaction.java:62)
org.apache.isis.core.runtime.transaction.facets.ActionInvocationFacetWrapTransaction$1#execute(ActionInvocationFacetWrapTransaction.java:59)
org.apache.isis.core.runtime.system.transaction.IsisTransactionManager#executeWithinTransaction(IsisTransactionManager.java:216)
org.apache.isis.core.runtime.transaction.facets.ActionInvocationFacetWrapTransaction#invoke(ActionInvocationFacetWrapTransaction.java:59)
org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionDefault#execute(ObjectActionDefault.java:363)
org.apache.isis.core.metamodel.specloader.specimpl.ObjectActionDefault#executeWithRuleChecking(ObjectActionDefault.java:351)
org.apache.isis.viewer.wicket.model.models.ActionModel#executeAction(ActionModel.java:468)
org.apache.isis.viewer.wicket.model.models.ActionModel#load(ActionModel.java:447)
org.apache.isis.viewer.wicket.model.models.ActionModel#load(ActionModel.java:80)
org.apache.wicket.model.LoadableDetachableModel#getObject(LoadableDetachableModel.java:124)
org.apache.isis.viewer.wicket.model.models.ActionModel#executeHandlingApplicationExceptions(ActionModel.java:549)
org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel#executeActionOnTargetAndProcessResults(ActionPanel.java:247)
org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel#executeActionAndProcessResults(ActionPanel.java:195)
org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel#buildGui(ActionPanel.java:106)
org.apache.isis.viewer.wicket.ui.components.actions.ActionPanel#<init>(ActionPanel.java:84)
org.apache.isis.viewer.wicket.ui.components.actions.ActionPanelFactory#createComponent(ActionPanelFactory.java:49)
org.apache.isis.viewer.wicket.viewer.registries.components.ComponentFactoryRegistryDefault#createComponent(ComponentFactoryRegistryDefault.java:128)
org.apache.isis.viewer.wicket.ui.components.widgets.linkandlabel.ActionLinkFactoryAbstract$1#onClick(ActionLinkFactoryAbstract.java:73)
org.apache.wicket.ajax.markup.html.AjaxLink$1#onEvent(AjaxLink.java:86)
org.apache.wicket.ajax.AjaxEventBehavior#respond(AjaxEventBehavior.java:146)
org.apache.wicket.ajax.AbstractDefaultAjaxBehavior#onRequest(AbstractDefaultAjaxBehavior.java:641)
sun.reflect.NativeMethodAccessorImpl#invoke0(NativeMethodAccessorImpl.java:-2)
sun.reflect.NativeMethodAccessorImpl#invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl#invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method#invoke(Method.java:497)
org.apache.wicket.RequestListenerInterface#internalInvoke(RequestListenerInterface.java:258)
org.apache.wicket.RequestListenerInterface#invoke(RequestListenerInterface.java:241)
org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler#invokeListener(ListenerInterfaceRequestHandler.java:250)
org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler#respond(ListenerInterfaceRequestHandler.java:236)
org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor#respond(RequestCycle.java:890)
org.apache.wicket.request.RequestHandlerStack#execute(RequestHandlerStack.java:64)
org.apache.wicket.request.cycle.RequestCycle#execute(RequestCycle.java:261)
org.apache.wicket.request.cycle.RequestCycle#processRequest(RequestCycle.java:218)
org.apache.wicket.request.cycle.RequestCycle#processRequestAndDetach(RequestCycle.java:289)
org.apache.wicket.protocol.http.WicketFilter#processRequestCycle(WicketFilter.java:259)
org.apache.wicket.protocol.http.WicketFilter#processRequest(WicketFilter.java:201)
org.apache.wicket.protocol.http.WicketFilter#doFilter(WicketFilter.java:282)
org.eclipse.jetty.servlet.ServletHandler$CachedChain#doFilter(ServletHandler.java:1667)
org.apache.shiro.web.servlet.AbstractShiroFilter#executeChain(AbstractShiroFilter.java:449)
org.apache.shiro.web.servlet.AbstractShiroFilter$1#call(AbstractShiroFilter.java:365)
org.apache.shiro.subject.support.SubjectCallable#doCall(SubjectCallable.java:90)
org.apache.shiro.subject.support.SubjectCallable#call(SubjectCallable.java:83)
org.apache.shiro.subject.support.DelegatingSubject#execute(DelegatingSubject.java:383)
org.apache.shiro.web.servlet.AbstractShiroFilter#doFilterInternal(AbstractShiroFilter.java:362)
org.apache.shiro.web.servlet.OncePerRequestFilter#doFilter(OncePerRequestFilter.java:125)
org.eclipse.jetty.servlet.ServletHandler$CachedChain#doFilter(ServletHandler.java:1667)
org.eclipse.jetty.servlet.ServletHandler#doHandle(ServletHandler.java:581)
org.eclipse.jetty.server.handler.ScopedHandler#handle(ScopedHandler.java:143)
org.eclipse.jetty.security.SecurityHandler#handle(SecurityHandler.java:548)
org.eclipse.jetty.server.session.SessionHandler#doHandle(SessionHandler.java:226)
org.eclipse.jetty.server.handler.ContextHandler#doHandle(ContextHandler.java:1114)
org.eclipse.jetty.servlet.ServletHandler#doScope(ServletHandler.java:511)
org.eclipse.jetty.server.session.SessionHandler#doScope(SessionHandler.java:185)
org.eclipse.jetty.server.handler.ContextHandler#doScope(ContextHandler.java:1048)
org.eclipse.jetty.server.handler.ScopedHandler#handle(ScopedHandler.java:141)
org.eclipse.jetty.server.handler.ContextHandlerCollection#handle(ContextHandlerCollection.java:213)
org.eclipse.jetty.server.handler.HandlerCollection#handle(HandlerCollection.java:109)
org.eclipse.jetty.server.handler.HandlerWrapper#handle(HandlerWrapper.java:119)
org.eclipse.jetty.server.Server#handle(Server.java:517)
org.eclipse.jetty.server.HttpChannel#handle(HttpChannel.java:302)
org.eclipse.jetty.server.HttpConnection#onFillable(HttpConnection.java:242)
org.eclipse.jetty.io.AbstractConnection$ReadCallback#succeeded(AbstractConnection.java:245)
org.eclipse.jetty.io.FillInterest#fillable(FillInterest.java:95)
org.eclipse.jetty.io.SelectChannelEndPoint$2#run(SelectChannelEndPoint.java:75)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume#produceAndRun(ExecuteProduceConsume.java:213)
org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume#run(ExecuteProduceConsume.java:147)
org.eclipse.jetty.util.thread.QueuedThreadPool#runJob(QueuedThreadPool.java:654)
org.eclipse.jetty.util.thread.QueuedThreadPool$3#run(QueuedThreadPool.java:572)
java.lang.Thread#run(Thread.java:745)
</pre>

**Comment by danhaywood** [comment]
@Meirtz thanks for your interest in Estatio and also in Apache Isis.  

For these issues, first could you identify which version (ideally, which commit SHA) you are using?  We don't release Estatio to maven central, and it's fast moving, so we need this info to reproduce any issues.


1) No references to be selected when creating new item (It tells me “Doesn’t match pattern." );

Which "item"?  Please provide a detailed explanation as to how to reproduce.


2) Cannot install fixtures and return first role because it throws an unexpected error (Details show below);

Looking at the stack trace, this seems to be because the FixtureScripts domain service cannot be found.  This is puzzling, because Estatio does have an implementation.  Again, need a reference.


3) I wonder if there’s any tutorials or user guide or any other document on setting and modifying this great masterpieces.

Are you interested in Estatio or in Apache Isis?  

If Estatio, well, "it is what it is".  There is a little documentation on its design here [1].  If you are interested in it as an estate management app for your own company (or to extend) then I would presume you have some knowledge of the business domain...?

But my guess is you might be more interested in Apache Isis itself as a development framework for writing your own webapps.  If that's the case, then Estatio is useful to learn from, but there is lots of info on the isis.apache.org website, and we always try to be as helpful as we can to any specific questions raised on the users@isis.a.o mailing list.

Thx
Dan

[1] https://github.com/estatio/estatio/blob/master/adocs/documentation/src/main/asciidoc/auditability.adoc
