### ISSUE TITLE
Menu Customization

### ISSUE THREAD

**Issue by footprintkenya** [estatio/estatio#14]
Is the menu customizable as per screen size or not? The menu works great in monitors above 1600*1024 but in 1366*768, the menus keep overlapping each other!
![screenshot 34](https://cloud.githubusercontent.com/assets/15627081/11558371/7d7815ec-99c3-11e5-943e-28fb60800bcd.png)

**Comment by danhaywood** [comment]
Short answer is no, this is not customizable.  But that's a feature that would need to be added to Apache Isis, not to Estatio itself.

We do have a JIRA ticket open for this, https://issues.apache.org/jira/browse/ISIS-977, I've added this GH issue to it as another example.

Thanks for your interest; gonna close since it basically is a duplicate.

Cheers
Dan
