### ISSUE TITLE
How to run estatio in production

### ISSUE THREAD

**Issue by LucianDavies** [estatio/estatio#37]
After deploying to tomcat the app has a tag at the bottom a red triangle indicating its run in production can some one point out which file I can tweak the env to make estatio run in production

**Comment by danhaywood** [comment]
You can enable production mode (rather than prototype) by editing the
'configuration' context-param in web.xml [1]

You will also most likely want to change the JDBC connection to some
external database, in persistor.properties [2]

This configuration can also be externalized outside of the WAR, [3]

HTH
Dan

[1] https://isis.apache.org/guides/rgcfg.html#_using_the_wicket_viewer.
[2] https://isis.apache.org/guides/rgcfg.html#_rgcfg_configuration-files
[3] http://isis.apache.org/guides/ugbtb.html#8.3.-externalized-configuration
