### ISSUE TITLE
question about persist and flush problem

### ISSUE THREAD

**Issue by jintonghuoya** [estatio/estatio#91]
Hi，I am working with isis，but I found that persistIfNotAlready  and getContainer().flush() operation （Deprecated） result
 is Inconsistency with the replacement of RepositoryService#persist and Transation.flush() in my IntegTest。
My scene is like this:when i create a lease item,i will create all terms of rent automaticly .As expected the number of terms should be 40,but i found that there is only 39.and i catch up the code，found that the first time pesist function dosent work at all. when i replace the RepositoryService#persist and Transation.flush() code with persistIfNotAlready  and getContainer().flush(),the result SHOWs right.
i dont know if there is something wrong with my code or there is some bug in isis when create Multi-level object association.

**Comment by danhaywood** [comment]
Since you closed this I'm guessing you figured out the issue.  In case it helps, note that persist() only queues up an insert, this is done at the end of the interaction.  Sometimes in an integ test it's can be necessary to use flush to simulate this, eg at the end of the "given" or "when".  Hope that helps
